apiVersion: v1
kind: Service
metadata:
  namespace: guest-namespace-step22
  name: guest-service
  labels:
    part-of: guest-part
    component: guest-backend-server
    name: guest
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: guest-part
    component: guest-backend-server
    name: guest
  ports:
    - port: 80
      targetPort: http
      nodePort: 30022
  type: NodePort
